#!/bin/bash
$EXPOSE_PATH/SPE-dependencies/kafka_2.11-0.10.2.2/bin/zookeeper-server-start.sh $EXPOSE_PATH/SPE-dependencies/kafka_2.11-0.10.2.2/config/zookeeper.properties &
sleep 10
$EXPOSE_PATH/SPE-dependencies/kafka_2.11-0.10.2.2/bin/kafka-server-start.sh $EXPOSE_PATH/SPE-dependencies/kafka_2.11-0.10.2.2/config/server.properties &
