#!/bin/bash
EXPOSE_PATH=$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/..")
experiment_id=$1
yaml_config=$2
java -jar $EXPOSE_PATH/Software-Framework/target/StreamProcessingExperimentFramework-1.0.0-jar-with-dependencies.jar --yaml-config $yaml_config --trace-folder ../traces --is-coordinator --coordinator-port 50000 --experiment-id $experiment_id
