#!/bin/bash
EXPOSE_PATH=$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/..")
number_threads=$1
client_ip=$(hostname -I | cut -d' ' -f1)
client_port=$2
coordinator_ip=$3
coordinator_port=$4
spe_coordinator_port=$5
node_id=$6
trace_path=$7/node-$node_id
unused_cpu_core=$8
BEAM_JAR=$EXPOSE_PATH/SPEs-plus-wrappers/beam-plus-wrapper/expose-wrapper/build/libs/beam-expose-wrapper-2.22.0-SNAPSHOT.jar
KAFKA_PATH=$EXPOSE_PATH/SPEs-plus-wrappers/beam-plus-wrapper/kafka
KAFKA_PATH=$KAFKA_PATH $EXPOSE_PATH/scripts/start-zookeeper /tmp/expose-beam-zookeeper
KAFKA_PATH=$KAFKA_PATH $EXPOSE_PATH/scripts/start-kafka /tmp/expose-beam-kafka-logs

mkdir -p $trace_path

if [[ -z $unused_cpu_core ]]
then
	EXPOSE_PATH=$EXPOSE_PATH java -Xms2g -classpath $BEAM_JAR no.uio.ifi.BeamExposeWrapper --client-ip $client_ip --client-port 9092 --coordinator-ip $coordinator_ip --coordinator-port $coordinator_port --spe-coordinator-port $spe_coordinator_port --node-id $node_id --trace-output-folder $trace_path
else
	EXPOSE_PATH=$EXPOSE_PATH taskset -c $unused_cpu_core java -Xms2g -Dthread.pool.size=$number_threads -XX:ActiveProcessorCount=$number_threads -Dakka.client.timeout:600s -Dakka.ask.timeout:600s -classpath $BEAM_JAR no.uio.ifi.BeamExposeWrapper --client-ip $client_ip --client-port 9092 --coordinator-ip $coordinator_ip --coordinator-port $coordinator_port --spe-coordinator-port $spe_coordinator_port --node-id $node_id --trace-output-folder $trace_path
fi
