#!/bin/bash
number_threads=$1
client_ip=$(curl https://ipinfo.io/ip)
client_port=$2
coordinator_ip=$3
coordinator_port=$4
node_id=$5
trace_path=$6/esper/port-$client_port
unused_cpu_core=$7
mkdir -p $trace_path

if [[ -z $unused_cpu_core ]]
then
	java -jar ~/SPEs/siddhi-wip/modules/siddhi-experiments/target/siddhi-experiments-5.0.1-SNAPSHOT-jar-with-dependencies.jar --client-ip $client_ip --client-port $client_port --coordinator-ip $coordinator_ip --coordinator-port $coordinator_port --node-id $node_id --trace-output-folder $trace_path
else
	taskset -c $unused_cpu_core java -Dthread.pool.size=$number_threads -XX:ActiveProcessorCount=$number_threads -jar ~/SPEs/siddhi-wip/modules/siddhi-experiments/target/siddhi-experiments-5.0.1-SNAPSHOT-jar-with-dependencies.jar --client-ip $client_ip --client-port $client_port --coordinator-ip $coordinator_ip --coordinator-port $coordinator_port --node-id $node_id --trace-output-folder $trace_path
fi

