#!/bin/bash
EXPOSE_PATH=$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/..")
number_threads=$1
client_ip=$(curl https://ipinfo.io/ip)
client_port=$2
coordinator_ip=$3
coordinator_port=$4
node_id=$5
trace_path=$6/siddhi/port-$client_port
unused_cpu_core=$7
mkdir -p $trace_path

cd $EXPOSE_PATH
if [[ -z $unused_cpu_core ]]
then
	EXPOSE_PATH=$EXPOSE_PATH java -jar ./SPEs-plus-wrappers/siddhi-plus-wrapper/modules/siddhi-experiments/target/siddhi-experiments-5.0.1-SNAPSHOT-jar-with-dependencies.jar --client-ip $client_ip --client-port 5$client_port --coordinator-ip $coordinator_ip --coordinator-port $coordinator_port --node-id $node_id --trace-output-folder $trace_path
else
	EXPOSE_PATH=$EXPOSE_PATH taskset -c $unused_cpu_core java -Dthread.pool.size=$number_threads -XX:ActiveProcessorCount=$number_threads -jar ./SPEs-plus-wrappers/siddhi-plus-wrapper/modules/siddhi-experiments/target/siddhi-experiments-5.0.1-SNAPSHOT-jar-with-dependencies.jar --client-ip $client_ip --client-port 5$client_port --coordinator-ip $coordinator_ip --coordinator-port $coordinator_port --node-id $node_id --trace-output-folder $trace_path
fi

