#!/bin/bash
EXPOSE_PATH=$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/..")
number_threads=$1
client_ip=$(curl https://ipinfo.io/ip)
client_port=$2
coordinator_ip=$3
coordinator_port=$4
node_id=$5
trace_path=$6/node-$node_id
unused_cpu_core=$7
BEAM_JAR=$EXPOSE_PATH/SPEs-plus-wrappers/beam-plus-wrapper/expose-wrapper/build/libs/beam-expose-wrapper-2.22.0-SNAPSHOT.jar

mkdir -p $trace_path

if [[ -z $unused_cpu_core ]]
then
	EXPOSE_PATH=$EXPOSE_PATH java -classpath $BEAM_JAR no.uio.ifi.BeamExposeWrapper --client-ip $client_ip --client-port 9092 --coordinator-ip $coordinator_ip --coordinator-port $coordinator_port --node-id $node_id --trace-output-folder $trace_path
else
	EXPOSE_PATH=$EXPOSE_PATH taskset -c $unused_cpu_core java -Dthread.pool.size=$number_threads -XX:ActiveProcessorCount=$number_threads -Dakka.client.timeout:600s -Dakka.ask.timeout:600s -classpath $BEAM_JAR no.uio.ifi.BeamExposeWrapper --client-ip $client_ip --client-port 9092 --coordinator-ip $coordinator_ip --coordinator-port $coordinator_port --node-id $node_id --trace-output-folder $trace_path
fi
