#!/bin/bash
#kafka_is_up=$(echo dump | nc localhost 2181 | grep brokers)
kafka_is_up=$(nc -vz localhost 9092 2>&1 | grep "succeeded")
kafka_is_alive=
if [[ ! -z $kafka_is_up ]]
then
	echo "Kafka is already up!"
fi
while [[ -z $kafka_is_up ]]
do
  while [[ -z $kafka_is_alive ]]
  do
    $KAFKA_PATH/bin/kafka-server-start.sh $KAFKA_PATH/config/server.properties &
    kafka_pid=$!
    sleep 1
    echo "Checking if pid $kafka_pid is alive"
    kafka_is_alive=$(ps cax | grep $kafka_pid)
    echo "$kafka_pid is alive: $kafka_is_alive"
  done
  kafka_is_alive=$(ps cax | grep $kafka_pid)
  sleep 1
#  kafka_is_up=$(echo dump | nc localhost 2181 | grep brokers)
  kafka_is_up=$(nc -vz localhost 9092 2>&1 | grep "succeeded")
done
