#!/bin/bash
#kafka_is_up=$(echo dump | nc localhost 2181 | grep brokers)
kafka_log=$1
kafka_is_up=$(nc -vz localhost 9092 2>&1 | grep "succeeded")
kafka_is_alive=
echo "Start of start-kafka script"
if [[ ! -z $kafka_is_up ]]
then
	echo "Kafka is already up!"
else
	rm -r $kafka_log
fi
while [[ -z $kafka_is_up ]]
do
  while [[ -z $kafka_is_alive ]]
  do
    $KAFKA_PATH/bin/kafka-server-start.sh $KAFKA_PATH/config/server.properties &
    kafka_pid=$!
    sleep $(( ( RANDOM % 5 )  + 5 ))
    echo "Checking if pid $kafka_pid is alive"
    kafka_is_alive=$(ps cax | grep $kafka_pid)
    echo "$kafka_pid is alive: $kafka_is_alive"
    kafka_is_up=$(nc -vz localhost 9092 2>&1 | grep "succeeded")
    if [[ ! -z $kafka_is_up ]]
    then
	    break
    fi
  done
  kafka_is_alive=$(ps cax | grep $kafka_pid)
  sleep $(( ( RANDOM % 5 )  + 5 ))
#  kafka_is_up=$(echo dump | nc localhost 2181 | grep brokers)
  kafka_is_up=$(nc -vz localhost 9092 2>&1 | grep "succeeded")
  echo "Kafka is alive: $kafka_is_alive, Kafka is up: $kafka_is_up"
done
echo "End of start-kafka script"
