#!/bin/bash
rootdir=$1

# Intel Xeon
yaml=/home/espen/Research/PhD/Private-WIP/stream-processing-benchmark-wip/Experiments/experiment-configurations/experiment-configuration-movsim-intel-xeon-vldb.yaml
experiment_directory=$rootdir/experiment-1
x_factor="Number subscribers"
./analyze $yaml $experiment_directory "$x_factor" "intel-xeon-experiment-1"
experiment_directory=$rootdir/experiment-2
x_factor="Number Queries"
./analyze $yaml $experiment_directory "$x_factor" "intel-xeon-experiment-2"
experiment_directory=$rootdir/experiment-3
x_factor="Number Queries"
./analyze $yaml $experiment_directory "$x_factor" "intel-xeon-experiment-3"
experiment_directory=$rootdir/experiment-4
x_factor="Number Queries"
./analyze $yaml $experiment_directory "$x_factor" "intel-xeon-experiment-4"
experiment_directory=$rootdir/experiment-5
x_factor="Number publishers"
./analyze $yaml $experiment_directory "$x_factor" "intel-xeon-experiment-5"
experiment_directory=$rootdir/experiment-6
x_factor="Number publishers and subscribers"
./analyze $yaml $experiment_directory "$x_factor" "intel-xeon-experiment-6"

